#!/usr/bin/env python3
"""Derive a WIDE control course from the shipped one, changing one thing.

Purpose: settle whether the boat cruises at 76% of `vx_max` because of tuning or
because of the course. The diagnosis under test is that `CostCritic` dominates
the cost function by an order of magnitude, so wherever inflated water lies
inside MPPI's 2.8 s horizon, slowing down is nearly free -- and buoys line the
whole channel.

The control has to change *only* the thing the diagnosis names. So:

* **Gate positions and headings are untouched.** Every gate keeps its exact
  (x, y, heading). Path length, turn angles and turn radii are therefore
  identical, and elapsed time is directly comparable to the 104.5 s baseline. A
  scaled-up course would have confounded gate width with corner radius.
* **Every channel gate is widened to 6.0 m.** With 0.20 m buoys that leaves
  5.6 m of free water; the padded footprint's half-beam is 0.60 m, so the hull
  edge sits 2.2 m from a buoy surface on the centreline against a 1.30 m
  inflation radius. The driving line is outside inflation entirely, with 0.9 m
  of wander to spare.
* **Free-standing buoys are removed** (the sprint's mark and obstacle stay --
  they are 19 m south and the sprint task needs them). Three of them sit within
  0.4 m of a gate-to-gate line: (18.0, 2.6), (26.5, 6.2) and (6.0, 31.5), the
  last being the buoy the journal records as historically troublesome.

Everything else -- buoy radii, the lidar plane, the docks, the water, the
physics step -- is inherited unchanged.

**How to read the result.** If the SHIPPED config now runs near 1.30 m/s with no
parameter changed, the speed deficit is inflation-in-the-horizon and the tight
channel is a course-specific problem rather than a tuning one. If it still
cruises at ~0.99 m/s on a course with no inflation anywhere near the line, then
the obstacle-dominance diagnosis is wrong and every arm built on it should be
abandoned before it is run.

    python3 tools/make_wide_course.py
    python3 src/roboboat_description/scripts/gen_course.py \\
        --course src/roboboat_description/config/course_wide.yaml \\
        --output src/roboboat_description/worlds/roboboat_course_wide.sdf
"""

from __future__ import annotations

import sys
from pathlib import Path

WS = Path(__file__).resolve().parent.parent
CFG = WS / 'src' / 'roboboat_description' / 'config'
SRC = CFG / 'course_default.yaml'
DST = CFG / 'course_wide.yaml'

GATE_WIDTH = 6.0
CHANNEL_GATES = ('start', 'chan_a', 'chan_b', 'chan_c', 'chan_d',
                 'speed_in', 'speed_out', 'return_a', 'return_b', 'finish')
KEEP_BUOYS = ('sprint_mark', 'sprint_obstacle')

BANNER = """# WIDE CONTROL COURSE -- generated by tools/make_wide_course.py, do not hand-edit.
#
# Derived from course_default.yaml with exactly two changes:
#   1. every channel gate widened to %.1f m (positions and headings untouched,
#      so path length, turn angles and turn radii are identical to the shipped
#      course and elapsed time is directly comparable);
#   2. free-standing buoys removed, except the sprint mark and obstacle.
#
# The point is to put the driving line outside the inflation field entirely:
# 5.6 m of free water, 0.60 m padded half-beam, so 2.2 m of hull-to-surface
# against a 1.30 m inflation_radius. Running the SHIPPED config here separates
# "the controller is mistuned" from "the course keeps inflated water inside
# MPPI's horizon".
#
# The task is named channel_wide so it can never be confused with the frozen
# `channel` contract in tuning/regression_channel.json.
""" % GATE_WIDTH


def main() -> int:
    lines = SRC.read_text().splitlines()
    out: list[str] = []
    section = None
    widened = dropped = 0

    for line in lines:
        stripped = line.strip()
        if stripped and not line.startswith((' ', '#', '-')) and stripped.endswith(':'):
            section = stripped[:-1]

        if section == 'gates' and stripped.startswith('- {name:'):
            name = stripped.split('name:')[1].split(',')[0].strip()
            if name in CHANNEL_GATES:
                before, _, after = line.partition('width:')
                value, comma, rest = after.partition(',')
                line = f'{before}width: {GATE_WIDTH}{comma}{rest}'
                widened += 1

        if section == 'buoys' and stripped.startswith('- {'):
            if not any(k in stripped for k in KEEP_BUOYS):
                dropped += 1
                continue

        if section == 'tasks' and stripped == '- name: channel':
            line = line.replace('- name: channel', '- name: channel_wide')

        out.append(line)

    if widened != len(CHANNEL_GATES):
        print(f'expected to widen {len(CHANNEL_GATES)} gates, widened {widened}',
              file=sys.stderr)
        return 1

    DST.write_text(BANNER + '\n'.join(out) + '\n')
    print(f'wrote {DST.relative_to(WS)}')
    print(f'  gates widened to {GATE_WIDTH} m : {widened}')
    print(f'  free-standing buoys dropped   : {dropped}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
